# PostgreSQL

development:
  adapter: postgresql
  encoding: unicode
  database: corpweb_development
  pool: 5
  username: xj
  password: lodenice
  
production:
  adapter: postgresql
  encoding: unicode
  database: corpweb_production
  pool: 5
  username: xj
  password: lodenice
  
test:
  adapter: postgresql
  encoding: unicode
  database: corpweb_test
  pool: 5
  username: xj
  password: lodenice  


