# PostgreSQL

development:
  adapter: postgresql
  encoding: unicode
  database: cms_development
  pool: 5
  username: xj
  password: lodenice
  
production:
  adapter: postgresql
  encoding: unicode
  database: cms_production
  pool: 5
  username: xj
  password: lodenice
  
test:
  adapter: postgresql
  encoding: unicode
  database: cms_test
  pool: 5
  username: xj
  password: lodenice  


